apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ name }}"
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: gatling-test
          image: deepak-9976/gatling-test
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: "{{ java_opts }}"
            - name: SIMULATION_NAME
              value: "{{ simulation_name }}"
      restartPolicy: Never

